### ISSUE TITLE
EngineFixes.dll support 

### ISSUE THREAD

**Issue by Kiaos** [tiltedphoques/TiltedOnline#116]
Tried running Tilted Online with SSE Engine Fixes. An older version of this mod worked. But the recent update broke the ability to use Reborn. I'm 90% sure that it was on SSE Engine Fixes end cause Reborn worked with an earlier version. OR an older version of Skyrim. Anyways should I ask the Mod author of Engine fixes to make a fix or you can you fix what's wrong.

here is what happened. 
![2021-04-08 (6)](https://user-images.githubusercontent.com/32118932/114091412-e5448280-9875-11eb-8aa9-2336cd9d4eb5.png)

BTW tried it without all the mods and just SSE engine and it gave same error. So its just the DLL.

**Comment by LordKanelsnegle** [comment]
Pretty sure SSE Engine Fixes has never been compatible, and now it's completely blacklisted as well. Probably about time someone closes this issue 🤔
