### ISSUE TITLE
[Bug/Feature] Transfer ownership of actor when actor goes out of scope

### ISSUE THREAD

**Issue by RobbeBryssinck** [tiltedphoques/TiltedOnline#117]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2415%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/tiltedphoques/TiltedOnline/issues/117)

Currently, when an actor goes out of scope (meaning that the actor either walks out of the owner's cell or the owner walks out of the actor's cell), the owner of that actor broadcasts to everyone in that cell to delete the actor on their client. At best, this is jarring for other players. At worst: since deleted actors cannot be respawned, that actor is effectively deleted from the other player's save forever.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $15.00)

- [<img src='https://avatars.githubusercontent.com/u/25708893?v=4' alt='lordkanelsnegle' width=24 height=24> lordkanelsnegle](https://issuehunt.io/u/lordkanelsnegle) ($15.00)

### Submitted pull Requests
- [#126 [Core] Grid cell system](https://issuehunt.io/r/tiltedphoques/TiltedOnline/pull/126)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/tiltedphoques/TiltedOnline/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by LordKanelsnegle** [comment]
Prerequisite for #39
