### ISSUE TITLE
Occasionally on cell change players will become invisible/disconnect

### ISSUE THREAD

**Issue by ronlanla** [tiltedphoques/TiltedOnline#12]
Upon entering a new cell some players may see each other whereas some will see none. A workaround for this is to load a save in a different cell then load the current save again.
I've only observed this in Skyrim SE 1.5.97

**Comment by Dragonisser** [comment]
Might also be related to this: https://github.com/tiltedphoques/TiltedOnline/issues/10

Tho afaik the current build doesn't handle player despawn and its also lacking some branches, which why this isnt the most uptodate code in terms of internal development. Im not completely sure what is missing.
