### ISSUE TITLE
Chose wrong executable when setting up tiltedonline.exe up.

### ISSUE THREAD

**Issue by IndubitablyO** [tiltedphoques/TiltedOnline#135]
Hi all,

I hope someone can help, when trying to set up the tilted online exe, on the first setup it asks you to choose the executable file you run with fallout. I chose f4se as that is technically what I use (when running mods).

Unfortunately, when I run tiltedonline now, all i get is couldn't find fallout 4 executable.

Can anyone please tell me how to change the executable file tiltedonline uses to boot the game?

Thanks!

**Comment by yamashi** [comment]
Use the game's exe, the loader will take care of f4se for you

**Comment by PhantomGamers** [comment]
OP was asking how to change the target exe after already choosing one with the first time setup.

**Comment by IndubitablyO** [comment]
@yamashi Phantom gamers is correct, I have essentially bricked my tiltedonline because every time I choose option 2) to play fallout, it automatically loads the wrong exe file, and says "couldn't find fallout exe".

I really want to find out how to change the target exe again. 

Thanks!

**Comment by Force67** [comment]
TiltedOnline.exe -r

IndubitablyO ***@***.***> schrieb am Do., 4. Nov. 2021, 11:26:

**Comment by IndubitablyO** [comment]
Absolutely amazing, thank you so much!
