### ISSUE TITLE
build out and question for anniversary edition

### ISSUE THREAD

**Issue by drakwolf** [tiltedphoques/TiltedOnline#137]
The build is out of date and out of order, it cannot be downloaded, besides, this will be compatible with the anniversary edition?

**Comment by Christian-Garrison-18** [comment]
@drakwolf  I emailed yamashi@live.com about the issue, hopefully will get attention soon. Go a head and contact as well if need.

**Comment by RobbeBryssinck** [comment]
The build being expired is not an issue, the open source repo is discontinued in favor for a closed source repo. Further explanations about the anniversary edition can be found here: https://www.reddit.com/r/SkyrimTogether/comments/qq8z47/dev_update_information_regarding_the_anniversary/
