### ISSUE TITLE
FIXES - Latest Build EXPIRED

### ISSUE THREAD

**Issue by Christian-Garrison-18** [tiltedphoques/TiltedOnline#138]
## Issue:
Latest build for windows is expired and cannot be downloaded.

## Proposed Solution:
Fix the expired download 😄

**Comment by PhantomGamers** [comment]
I haven't tried it but I imagine you can just fork this repo and run the workflow yourself to generate a build

**Comment by Christian-Garrison-18** [comment]
> I haven't tried it but I imagine you can just fork this repo and run the workflow yourself to generate a build

Unfortunately the workflows are not setup for manual run builds, however so just sending a commit to master with a small readme change may do the trick. I'll see what happens

**Comment by Christian-Garrison-18** [comment]
No luck here https://github.com/Christian-Garrison-18/TiltedOnline/actions

**Comment by Christian-Garrison-18** [comment]
@PhantomGamers Did not work for me when forking, not sure why. But I emailed yamashi@live.com about the issue, hopefully will get attention soon. Go ahead and contact as well if need.

**Comment by lostcrusader99** [comment]
Guessing there has been no further update as of yet?

**Comment by RobbeBryssinck** [comment]
Tilted online is not released yet. This is a development build. The only reason you'd want to download this is for development purposes. This build is not meant to be played by normal users. You'll have to wait until the mod fully releases.

**Comment by davidchalifoux** [comment]
> Tilted online is not released yet. This is a development build. The only reason you'd want to download this is for development purposes. This build is not meant to be played by normal users. You'll have to wait until the mod fully releases.

I feel like there should be a disclaimer on the wiki then.
![image](https://user-images.githubusercontent.com/3289533/144944647-e2534d4e-8b6e-4cb1-aa2b-d53cf6a2fe8a.png)

**Comment by lostcrusader99** [comment]
> > Tilted online is not released yet. This is a development build. The only reason you'd want to download this is for development purposes. This build is not meant to be played by normal users. You'll have to wait until the mod fully releases.
> 
> I feel like there should be a disclaimer on the wiki then. ![image](https://user-images.githubusercontent.com/3289533/144944647-e2534d4e-8b6e-4cb1-aa2b-d53cf6a2fe8a.png)

Yeah, there isn't anything that states that on the Wiki...

**Comment by RobbeBryssinck** [comment]
I'll change the wiki to reflect that.
