### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by HcGxGrill** [tiltedphoques/TiltedOnline#16]
Followed the GETTINGSTARTED.md to the letter and I am unable to compile for either Skyrim/Fallout 4.

It builds 20/23 of the projects failing on Script, Client and Server.

Using VS2019 Community Edition. Not sure if this is just an issue on my end.

**Comment by yamashi** [comment]
Errors with sol.hpp I suppose ? Multiple people have reported that downloading the latest sol.hpp from the master did the trick

**Comment by HcGxGrill** [comment]
I'll give this a try, thank you! I'll update here if it worked.

**Comment by HcGxGrill** [comment]
Yes downloading the newest sol.hpp did the trick. Thank you!

**Comment by yamashi** [comment]
I updated it in the repo as well :)
