### ISSUE TITLE
How to connect to my server?

### ISSUE THREAD

**Issue by Def0lttGit** [tiltedphoques/TiltedOnline#20]
I have setled up my server, the console with it is running fine, though I dont get how to connect to it. Can you please tell me? (Talking about fallout4)

**Comment by Dragonisser** [comment]
https://github.com/tiltedphoques/TiltedOnline/blob/master/GETTINGSTARTED.md#verifying

**Comment by Def0lttGit** [comment]
> https://github.com/tiltedphoques/TiltedOnline/blob/master/GETTINGSTARTED.md#verifying

Thx
