### ISSUE TITLE
Enforce code guidelines through Clang Format or similar

### ISSUE THREAD

**Issue by fylux** [tiltedphoques/TiltedOnline#21]
In order to ensure a consisten coding style throught the project, I believe that it would be helpful to rely on automatic formatting tools rather than on an informal guideline. Moreover, it would minimize the noise when reviewing diffs in PRs.

**Comment by yamashi** [comment]
That's a good idea, I don't have any experience with that so help wanted :)

**Comment by Force67** [comment]
I recommend checking out an online tool such as https://zed0.co.uk/clang-format-configurator/ for creating a fitting clang format file.  Visual Studio 2017+ automatically detect the presence of the .clang-format and format upon saving the code.
