### ISSUE TITLE
Cannot Get Reverse Console to Launch on Secondary Machine

### ISSUE THREAD

**Issue by massdivide** [tiltedphoques/TiltedOnline#23]
Attempting to test between two machines.

What are the direct requirements for executing the Loader.exe? (Client)
--[[ Is direct x sdk a requirement?
---[[Is Nodejs a requirement?

I installed both on my secondary test machine. No reverse console.
tp_loader.conf changes have zero impact.

[Root Directory] ->
E:\SteamGames\steamapps\common\Skyrim Special Edition\
      SkyrimSE.exe
      Loader.exe
      SkyrimTogether.dll
      //All other Required Files 1-1 copy//
tp_loader.conf ->

GameId64=489830
GamePath64=./SkyrimSE.exe
DllRelease=./SkyrimTogether.dll
GameId32=72850
GamePath32=TESV.exe
DllDebug=SkyrimTogether_d.dll

Machine A: Reverse Console launches CEF loads, can join server.
Machine B: Skyrim launches, no console.

Tried with Standard and Elevated Privs.

**Comment by Dragonisser** [comment]
![image](https://user-images.githubusercontent.com/4233773/83968168-8c0f6980-a8c7-11ea-934e-20ebe5330b73.png)

Are you sure copied all that over? Its not necessary to copy the files inside the Skyrim folder, make a separate folder and change the GamePath64 accordingly.

```
GameId64=489830
GamePath64=F:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\SkyrimSE.exe
DllRelease=SkyrimTogether.dll
DllDebug=SkyrimTogether_d.dll
```

**Comment by massdivide** [comment]
[https://media.discordapp.net/attachments/338491760005218304/719267566664679556/TestMachine.PNG?width=914&height=501](url)

Replicated your setup. No change. No reverse Console on Machine B. Same result. 

Is Visual Studio a requirement? That is the only anomaly between the two machines.

**Comment by WopsS** [comment]
Do you have Visual C++ Redistributable installed on your second machine? If not get the latest version from [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

**Comment by massdivide** [comment]
> Do you have Visual C++ Redistributable installed on your second machine? If not get the latest version from [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

Doesn't Directx SDK install vs C++ 2010 by default?

**Comment by WopsS** [comment]
VC++ 2010 is not necessary, since this project use C++17 you need at least VC++ 2017.

**Comment by massdivide** [comment]
> VC++ 2010 is not necessary, since this project use C++17 you need at least VC++ 2017, latest is preferable.

Double checked, has both x86 and x64. Still no reverse console.

**Comment by Annihlator** [comment]
I ran into the same issue, untill i decided on a hunch to try and move the installdir of FO4 to my steamlibrary located in C:/Program Files(x86)/Steam/ instead of on my D-drive, after that suddenly the secondary machine *would* have F4SE launched along with it and the UI showed up. Before that i got no reverse console, nor reports from F4SE upon entering "getf4seversion" in the console on the secondary machine.

**Comment by Dragonisser** [comment]
> > VC++ 2010 is not necessary, since this project use C++17 you need at least VC++ 2017, latest is preferable.
> 
> Double checked, has both x86 and x64. Still no reverse console.

Run into the same problem when ive tried it on my laptop. Thought i might give it a try and compile it there too which fixed the issue. I havent actually tried to use the old files, so it either might be a bug with the compilation or a missing dependency that is resolved by installing python3.8, Directx10SDK and Visual Studios.

Ill update here when i tried with the files from my pc.

**Comment by massdivide** [comment]
> > > VC++ 2010 is not necessary, since this project use C++17 you need at least VC++ 2017, latest is preferable.
> > 
> > 
> > Double checked, has both x86 and x64. Still no reverse console.
> 
> Run into the same problem when ive tried it on my laptop. Thought i might give it a try and compile it there too which fixed the issue. I havent actually tried to use the old files, so it either might be a bug with the compilation or a missing dependency that is resolved by installing python3.8, Directx10SDK and Visual Studios.
> 
> Ill update here when i tried with the files from my pc.

Appreciate it

**Comment by zxyxz** [comment]
File **tp_loader.conf** contains **incorrect** and **invisible** characters
