### ISSUE TITLE
Occasionally on cell change NPCs are stripped of clothing and no longer move/interact with the player.

### ISSUE THREAD

**Issue by JonathanRiggins** [tiltedphoques/TiltedOnline#33]
I built Master 12a58f4 and found that on cell change while another player is connected can cause all NPCs to be stripped and don't interact with the player as intended. The shops and dialogues still work but voice lines and the NPCs that force the player to interact (EX: courier) no longer function as intended. They also seem not to move properly. This seems to break the save as well as I loaded the autosave in which this event occurred after disconnecting and noticed the NPCs inert state immediately.

**Comment by Dragonisser** [comment]
It was just the initial commit for the feature, its not done
