### ISSUE TITLE
[Features] Actor values

### ISSUE THREAD

**Issue by yamashi** [tiltedphoques/TiltedOnline#38]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24250%20Funded-%2300A156.svg" />](https://issuehunt.io/r/tiltedphoques/TiltedOnline/issues/38)

The client sets health, mana etc and this is not synchronized.

The challenge is that the client is not deterministic meaning if Player A hits NPC B, on Player A's client it might hit correctly and apply the effects but it might not on another player's client. Who controls the damage ? I think the best would be to register to the damage events and the owner of the NPC triggering the event will be the one to send the delta damage, other events should be canceled.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $250.00)

- [<img src='https://avatars2.githubusercontent.com/u/672982?v=4' alt='yamashi' width=24 height=24> yamashi](https://issuehunt.io/u/yamashi) ($50.00)
- [<img src='https://avatars1.githubusercontent.com/u/68261930?v=4' alt='wind0s' width=24 height=24> wind0s](https://issuehunt.io/u/wind0s) ($50.00)
- [<img src='https://avatars.githubusercontent.com/u/14268336?v=4' alt='prazon' width=24 height=24> prazon](https://issuehunt.io/u/prazon) ($100.00)
- $50.00 have been anonymously funded.

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/tiltedphoques/TiltedOnline/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by storm-ace** [comment]
Will it not make sense if the server store an event-based time system?

Let say you cast an attack of any form, that gets stored in a dict with a timestamp, and the attack's class
this way we got temp data of the entity health in that current time frame
then after the dict get a set range and time between each key it ships it back to each socket
that way the server acts as the ruler over the moment
