### ISSUE TITLE
[Crash] Pickpocketing crashes the client if the NPC changes the inventory content

### ISSUE THREAD

**Issue by yamashi** [tiltedphoques/TiltedOnline#52]
With two players connected to a server A and B.
1) A starts pick pocketing player B
2) Player B modifies their inventory 
3) A crashes

Potential fix : Cache inventory changes received while in menus and apply them when possible.

**Comment by massdivide** [comment]
Potential hotfix: Disable Pickpocketing players and enable opt-in server setting.

**Comment by Dejauxvue** [comment]
fixed by #82
