### ISSUE TITLE
Sol dependency build issue

### ISSUE THREAD

**Issue by cj-atmoscape** [tiltedphoques/TiltedOnline#54]
Hi all,

I'm unable to build the solution out of the box. The Client, Server & Script projects fail to build. I believe the problem is with the sol dependency? I haven't coded C++ in 10 years, so this is a bit beyond me at the moment. I'm going to continue to look into this, but it'll be slow going. If anyone has experienced this issue, is a C++ guru or is gifted in divination, some guidance would be greatly appreciated.

These are the steps I've taken - on Windows 10 x64:
1. Installed VS 2019 Community
2. Uninstalled old C++ 2010 redist
3. Ran DXSDK_Jun10 installer
4. Cloned repo and ran submodule sync commands
5. Ran 2019 project initialization .bat file
6. Opened solution in VS 2019 Community
7. Changed build config to "Skyrim" via "Build" -> "Configuration Manager"
8. Built solution
9. Rebuilt solution so only pertinent errors were printed

See [tilted_online_build_errors.txt](https://github.com/tiltedphoques/TiltedOnline/files/5038456/tilted_online_build_errors.txt) for build errors.

Thanks!

**Comment by Dragonisser** [comment]
https://github.com/tiltedphoques/TiltedOnline/issues/16

**Comment by kuromiii** [comment]
Same issue after upgrading to VS2019 16.7 -> https://github.com/ThePhD/sol2/issues/1008

**Comment by SirLynix** [comment]
This isn't related to #16 as this issue appeared with VS 2019 16.7 and is not fixed by upgrading to the latest version of sol3.

**Comment by yamashi** [comment]
@SirLynix  yeet sol

**Comment by PhantomGamers** [comment]
It builds with the VS 2019 16.8 preview from https://visualstudio.microsoft.com/vs/preview/
