### ISSUE TITLE
node-gyp error when npm installing skyrim_ui

### ISSUE THREAD

**Issue by bantmen** [tiltedphoques/TiltedOnline#66]
**Background**

I have installed Visual Studio 16.8 (see https://github.com/tiltedphoques/TiltedOnline/issues/61) to successfully build the project. Then I have followed to rest of the instructions and opened the game through the loader.exe which brings me to

![image](https://user-images.githubusercontent.com/6361222/91619835-3ee9e380-e95c-11ea-8e71-adbac90b8209.png)

**Issue**

Assuming that the red rectangle was an indicator of the skyrim_ui requiring a build, I've ran `npm install`:

```
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Etrag\\personal\\TiltedOnline\\Code\\skyrim_ui\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Etrag\personal\TiltedOnline\Code\skyrim_ui\node_modules\node-sass
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 (node_modules\node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

https://github.com/nodejs/node-gyp/issues/1747 seems to be relevant but I could not get the installation working.

**Comment by Etragas** [comment]
@Wopss in discord suggested either:
1. Setting just adding "node-sass": "4.14.1" in packages.json
or 
2. Try to build off this pr https://github.com/tiltedphoques/TiltedOnline/pull/62

Someone test option 1 and it let them build the project

**Comment by Dumbeldor** [comment]
It's fixed on my branch ;) But it's still on WIP.

**Comment by Force67** [comment]
The red rectangle is a debug online indicator..

**Comment by Dragonisser** [comment]
@bantmen it works fine in @Dumbeldor branch. It also got updated to the latest commits now which means someone can work on it to implement all the features again.

https://github.com/Dumbeldor/TiltedOnline/tree/update_ui_angular_10
