### ISSUE TITLE
Tkv6 ReShade compatibility?

### ISSUE THREAD

**Issue by diegito55** [tiltedphoques/TiltedOnline#72]
I recently installed Tkv6 ReShade, but now the UI Menu is invisible. I can tell the menu gets activated because of the arrow that pops up, but the menu is invisible.

**Comment by diegito55** [comment]
I just wanna ask if there is anything I can do other than uninstall the shader? Could I temporarily disable the use of DX from the Shader? I really would love to use this shader

**Comment by yamashi** [comment]
We can't do much about this, I don't think you will be able to use the modified renderer.
